all:
	g++ -o bronze1.out bronze1.cpp -DTEST
	g++ -o bronze2.out bronze2.cpp -DTEST
	g++ -o bronze3.out bronze3.cpp -DTEST
	g++ -o silver1.out silver1.cpp -DTEST
	g++ -o silver2.out silver2.cpp -DTEST
	g++ -o silver3.out silver3.cpp -DTEST
	g++ -o gold1.out gold1.cpp -DTEST
	g++ -o gold2.out gold2.cpp -DTEST
	g++ -o gold3.out gold3.cpp -DTEST
	g++ -o gold3_after_contest.out gold3_after_contest.cpp -DTEST

clean:
	rm *.out
